routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ZoneController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\DepartmentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('employee', EmployeeController::class);
Route::resource('zones',    ZoneController::class);
Route::get('/departments',  [DepartmentController::class, 'index'])  ->name('department.index');

app/Models/Zone.php
<?php

namespace App\Models;

use App\Models\Employee;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Zone extends Model
{
    use HasFactory;

    public function getEmployee(){

        if (!is_null($this->employee_id)){
            $query = Employee::where('id', $this->employee_id)->first();
            $fullName = "{$query->first_name} {$query->last_name}";
            return  $fullName;
        }

    }

    public function employees(){
        return $this->hasMany(Employee::class);
    }
}

app/Http/Controllers/ZoneController.php
<?php

namespace App\Http\Controllers;

use App\Models\Zone;
use App\Models\Employee;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;

class ZoneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        
        $zones = Zone::get();

        return view('zones.index', [
            'zones' => $zones,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $departments = HTTP::get('https://intcomex-test.apigee.net/v1/getplaces?locale=es&countryId=Co&apiKey=5012b669-f1eb-4eb4-bda8-d69d1ada3086&utcTimeStamp=2020-05-07T21:00:11.071Z&signature=b43f6d5eb1f9fa98388f2b69b01dabc1c6046e8f7a87e3ca99efe2d4dae04ba0')->json();
        $employees = Employee::get();

        return view('zones.create', [
            'departments' => $departments,
            'employees' => $employees
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $datosZone = request()->except('_token');

        Zone::insert($datosZone);

        return redirect('zones');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/zones/create.blade.php
<h1>Crear Zona</h1>

<form action="{{ route('zones.store') }}" method="post" enctype="multipart/form-data">
    @csrf
    @include('zones.form')
</form>

resources/views/zones/form.blade.php
<label for="first_name">Empleado</label>
<select class="form-control select2" name="employee_id" id="employee_id" title="Empleado" data-size="7">
    <option disabled selected>Escoja el empleado...</option>
    @foreach ($employees as $employee)
        <option value="{{ $employee->id }}"
        >{{ $employee->first_name }} {{ $employee->last_name }}</option>
    @endforeach
</select>
<br>

<label for="last_name">Departamento</label>
<select class="form-control select2" name="department_id" id="department_id" title="Departamento" data-size="7">
    <option disabled selected>Escoja el departamento...</option>
    @foreach ($departments as $department)
        <option value="{{ $department['Id'] }}"
        >{{ $department['Name']}}</option>
    @endforeach
</select>
<br>

<br>

<input type="submit">

resources/views/zones/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zonas</title>
</head>
<body>
    <h1>Zonas</h1> <a href="{{ route('zones.create') }}">Crear Nueva Zona</a>
    <br>
    <table class="table table-light">
        <thead class="thead thead-light">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Empleado</th>
            <th scope="col">Zona</th>
          </tr>
        </thead>
        <tbody>
            @foreach ($zones as $zone)
                <tr>
                    <th scope="row">{{ $zone->id }}</th>
                    <td>{{ $zone->getEmployee() }}</td>
                    <td>{{ $zone->department_id }}</td>
                </tr>
            @endforeach
        </tbody>
      </table>
</body>
</html>