routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ZoneController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\DepartmentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('employee', EmployeeController::class);
Route::resource('zones',    ZoneController::class);
Route::get('/departments',  [DepartmentController::class, 'index'])  ->name('department.index');

app/Models/Employee.php
<?php

namespace App\Models;

use App\Models\Department;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Employee extends Model
{
    use HasFactory;

    public function zones(){
        return $this->hasMany(Zone::class);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $employees = Employee::paginate(5);
;
       /*  dd($employees); */

        return view('employees.index', [

            'employees' => $employees,

        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('employees.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $datosEmployee = request()->except('_token');

        Employee::insert($datosEmployee);

        return redirect('employee');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $employee = Employee::findOrFail($id);

        return view('employees.edit', [
            'employee' => $employee,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $datosEmployee = request()->except('_token', '_method');

        Employee::where('id', $id)->update( $datosEmployee);

        return redirect('employee');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Employee::destroy($id);
        return redirect('employee');
    }
}

resources/views/employees/create.blade.php
<h1>Crear Empleado</h1>

<form action="{{ route('employee.store') }}" method="post" enctype="multipart/form-data">
    @csrf
    @include('employees.form')
</form>

resources/views/employees/edit.blade.php
<h1>Editar Empleado</h1>

<form action="{{ route('employee.update', $employee->id) }}" method="post" enctype="multipart/form-data">
    @csrf
    {{ method_field('PATCH') }}
    @include('employees.form')
</form>

resources/views/employees/form.blade.php
<label for="first_name">Nombres</label>
<input type="text" name="first_name" id="first_name" value="{{ isset($employee->first_name) ? $employee->first_name:''  }}">
<br>

<label for="last_name">Apellidos</label>
<input type="text" name="last_name" id="last_name" value="{{ isset($employee->last_name) ? $employee->last_name:'' }}">
<br>

<label for="birthday">Cumpleaños</label>
<input type="date" name="birthday" id="birthday" value="{{ isset($employee->birthday) ? $employee->birthday:'' }}">
<br>

<label for="gender">Genero</label>
<input type="text" name="gender" id="gender" value="{{ isset($employee->gender) ? $employee->gender:'' }}">
<br>

<label for="hire">Fecha Contrato </label>
<input type="date" name="hire" id="hire" value="{{ isset($employee->hire) ? $employee->hire:'' }}">
<br>

<input type="submit">

resources/views/employees/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Empleados</title>
</head>
<body>
    <h1>Empleados</h1> <a href="{{ route('employee.create') }}">Crear Nuevo</a>
    <br>
    <table class="table table-light">
        <thead class="thead thead-light">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nombres</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Cumpleaños</th>
            <th scope="col">Genero</th>
            <th scope="col">Fecha Contrato</th>
            <th scope="col">Acciones</th>
          </tr>
        </thead>
        <tbody>
            @foreach ($employees as $employee)
                <tr>
                    <th scope="row">{{ $employee->id }}</th>
                    <td>{{ $employee->first_name }}</td>
                    <td>{{ $employee->last_name }}</td>
                    <td>{{ $employee->birthday }}</td>
                    <td>{{ $employee->gender }}</td>
                    <td>{{ $employee->hire }}</td>
                    <td>
                        <a href="{{ url('employee/'. $employee->id. '/edit') }}">Editar</a>
                        |
                        <form action="{{ url('employee/'. $employee->id) }}" method="post">
                            @csrf
                            {{ method_field('DELETE') }}
                            <input type="submit" onclick="return confirm('Desea borrar ?')" value ="Borrar">
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
      </table>
</body>
</html>